# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blankwindow3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btencender = QtWidgets.QPushButton(self.centralwidget)
        self.btencender.setGeometry(QtCore.QRect(250, 420, 101, 71))
        self.btencender.setObjectName("btencender")
        self.btapagar = QtWidgets.QPushButton(self.centralwidget)
        self.btapagar.setGeometry(QtCore.QRect(440, 420, 101, 71))
        self.btapagar.setObjectName("btapagar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.label.setObjectName("label")
        self.imagen_label = QtWidgets.QLabel(self.centralwidget)
        self.imagen_label.setGeometry(QtCore.QRect(480, 60, 221, 161))
        self.imagen_label.setObjectName("imagen_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btencender.setText(_translate("MainWindow", "Boton 1"))
        self.btapagar.setText(_translate("MainWindow", "Boton 2"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.imagen_label.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
